apiVersion: v1
kind: ServiceAccount
metadata:
  name: eva02-sa
  namespace: eva02

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eva02-role
  namespace: eva02
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eva02-rolebinding
  namespace: eva02
subjects:
- kind: ServiceAccount
  name: eva02-sa
  namespace: eva02
roleRef:
  kind: Role
  name: eva02-role
  apiGroup: rbac.authorization.k8s.io
